### ISSUE TITLE
How to generate the hier and geo format from our own datasets.

### ISSUE THREAD

**Issue by jiayaozhang** [daerduoCarey/structedit#1]
Dear @daerduoCarey 
After I have looked through all the paper details, I didn't find any code explaining how to generate npz and a JSON file with ref_sym, trans_sym, rot_sym with new datasets.  Since the code in gen_synshape from structuredit is to randomly sample the model and then turn it into structedit JSON format.  And the output npz and JSON seem to be different from the partner annotation system, and the npz data generation has not been mentioned in structurenet and partnet. 

So I wonder could you please provide the code about how to generate the npz and JSON file data from our own datasets.

![Screenshot from 2021-03-02 11-38-07](https://user-images.githubusercontent.com/38579506/109621616-42993580-7b4c-11eb-80ce-4b75a1e25427.png)

Thanks a lot!

**Comment by daerduoCarey** [comment]
synshapes is synthetic shapes, which are different from partnet data.

**Comment by jiayaozhang** [comment]
Thanks for the timely reply! Appreciate it a lot!

So if I have some synthetic shapes generated by myself and it's much more complicated than chair and sofa

 how could I create the JSON file and NPZ file then?

**Comment by daerduoCarey** [comment]
the files should explain themselves very well. I suggest you try to understand the data in json/npz files and then you know how to make them. I have no code to release for preparing the data as different data requires different scripts to generate these json/npz files.
